name: CI


on:
  push:
    branches: 
     -main

jobs:
    build-and-push:
     name: 'Build and Push'
     runs-on: ubuntu-latest

     steps:
       - name: Checkout
       - uses: actions/checkout@v4

       -name: Build docker image
       run: docker build -t margaridadiamantino/nlw.journey.api:latest .